/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as CodeAreaImport } from './routes/CodeArea'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AuthVerifyIndexImport } from './routes/auth/verify/index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const CodeAreaRoute = CodeAreaImport.update({
  id: '/CodeArea',
  path: '/CodeArea',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerifyIndexRoute = AuthVerifyIndexImport.update({
  id: '/auth/verify/',
  path: '/auth/verify/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/CodeArea': {
      id: '/CodeArea'
      path: '/CodeArea'
      fullPath: '/CodeArea'
      preLoaderRoute: typeof CodeAreaImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/verify/': {
      id: '/auth/verify/'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/CodeArea': typeof CodeAreaRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthIndexRoute
  '/auth/verify': typeof AuthVerifyIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/CodeArea': typeof CodeAreaRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthIndexRoute
  '/auth/verify': typeof AuthVerifyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/CodeArea': typeof CodeAreaRoute
  '/about': typeof AboutRoute
  '/auth/': typeof AuthIndexRoute
  '/auth/verify/': typeof AuthVerifyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/CodeArea' | '/about' | '/auth' | '/auth/verify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/CodeArea' | '/about' | '/auth' | '/auth/verify'
  id: '__root__' | '/' | '/CodeArea' | '/about' | '/auth/' | '/auth/verify/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeAreaRoute: typeof CodeAreaRoute
  AboutRoute: typeof AboutRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthVerifyIndexRoute: typeof AuthVerifyIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeAreaRoute: CodeAreaRoute,
  AboutRoute: AboutRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthVerifyIndexRoute: AuthVerifyIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/CodeArea",
        "/about",
        "/auth/",
        "/auth/verify/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/CodeArea": {
      "filePath": "CodeArea.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/auth/verify/": {
      "filePath": "auth/verify/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
